# Periféricos base
CONFIG_GPIO=y
CONFIG_SPI=y

# Logs y manejo de decimales (Float) críticos para la impedancia
CONFIG_LOG=y
CONFIG_CBPRINTF_FP_SUPPORT=y

CONFIG_PICOLIBC=y

# Aumentar la pila para la lógica del AD5940
CONFIG_MAIN_STACK_SIZE=4096


# Forzar la activación de la consola por puerto serie (UART)
CONFIG_SERIAL=y
CONFIG_CONSOLE=y
CONFIG_UART_CONSOLE=y

# Forzar al núcleo de aplicación a no esperar al núcleo de red
CONFIG_BOARD_ENABLE_CPUNET=n

# 1. Ignorar el cristal de cuarzo externo de 32kHz y usar el oscilador RC interno (A prueba de fallos)
CONFIG_CLOCK_CONTROL_NRF_K32SRC_RC=y

# 2. Forzar a que los logs salgan INMEDIATAMENTE. Si hay un crash, lo veremos antes de que muera.
CONFIG_LOG_MODE_IMMEDIATE=y

# 3. Evitar que la placa se reinicie infinitamente si hay un error fatal (Kernel Panic)
CONFIG_RESET_ON_FATAL_ERROR=n